# -*- coding: utf-8 -*-
"""Mohit kumar,BCA2nd,A,P-1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PstKTWikVk3tWVOjAryWDTK7-7TqVw_C

Project 1 (Petrol Consumption Data Analysis)
Mohit Kumar
BCA 2nd yr, A
Year-(2020-2023)
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

#Importing the data using pandas to read csv file:-

data=pd.read_csv("D:\BCA III\ML(python)\ML Projects/petrol_consumption.csv")
data.head(5)

#Checking Rows and columns 

data.shape

#Checking Null values in Dataset

data.isnull().sum()
data.head(4)

#changing name of columns using .rename

data.rename(columns = {'Population_Driver_licence(%)':'P_D_L'}, inplace = True)
data.head(4)

#Perform descriptive statistics and calculate mean, median etc

data.describe()

#To create boxplot we are using seaborn as sns

sns.boxplot(data.P_D_L)

#corr() is used to find the pairwise correlation of all columns in the dataframe

data.corr()
sns.heatmap(data.corr(),annot=True)

#Plotting graph using matplotlib.pyplot as plt

plt.xlabel("P_D_L")
plt.ylabel("Petrol_Consumption")
plt.scatter(data.P_D_L,data.Petrol_Consumption,color="red",marker=".")

'''
Applying linear regression 
Linear regression is a statistical method for modeling relationships between
a dependent variable with a given set of independent variables.
y=a+bx
The independent variable is x and the dependent variable is y.
'''

from sklearn import linear_model
model=linear_model.LinearRegression()
model.fit(data[["P_D_L"]],data.Petrol_Consumption)
model

#Using train test split Method to Train Data

from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(data[['P_D_L']],data[['Petrol_Consumption']],train_size=0.7)

X_test
X_train
y_train
y_test
y_predicted=model.predict(X_test)

model.predict([[0.356]])

#Creating graph uing predicted linear

plt.scatter(data.P_D_L,data.Petrol_Consumption,color="red",marker=".")
plt.plot(data.P_D_L,model.predict(data[["P_D_L"]]))